language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - pip install tox tox-pyenv

script:
  - tox
