---
name: CI
on: [push]
jobs:
  python311-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt install
      run: cat Aptfile | sudo xargs apt-get install

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Poetry install
      run: pip install -Iv poetry

    - name: Install dependencies
      run: poetry install -v

    - name: Tests
      run: poetry run pytest

    - name: Linting
      run: |
        poetry run ruff check social_auth_mitxpro/
        poetry run ruff format --check

  python38-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt install
      run: cat Aptfile | sudo xargs apt-get install


    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Poetry install
      run: pip install -Iv poetry

    - name: Install dependencies
      run: poetry install -v

    - name: Tests
      run: poetry run pytest

    - name: Linting
      run: |
        poetry run ruff check social_auth_mitxpro/
        poetry run ruff format --check
