---
name: CI
on: [push]
jobs:
  python311-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt install
      run: cat Aptfile | sudo xargs apt-get install

    - name: Python setup
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: "3.11"

    - id: cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Poetry install
      run: pip install -Iv poetry

    - name: Install dependencies
      run: poetry install -v

    - name: Tests
      run: poetry run pytest

    - name: Linting
      run: |
        poetry run ruff check social_auth_mitxpro/
        poetry run ruff format --check

  python38-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt install
      run: cat Aptfile | sudo xargs apt-get install


    - name: Python setup
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: "3.8"

    - id: cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Poetry install
      run: pip install -Iv poetry

    - name: Install dependencies
      run: poetry install -v

    - name: Tests
      run: poetry run pytest

    - name: Linting
      run: |
        poetry run ruff check social_auth_mitxpro/
        poetry run ruff format --check
